import type { Metadata } from "next";
import { photos } from "@/data/photos";
import { wordmark } from "@/site.config";
import PhotosBoard from "@/components/photos-board";

// /photos — the loose masonry board (V4). Everything unfiled: no captions to read,
// no story to follow. The board head sits over a CSS-columns masonry (client
// component) of next/image tiles, each opening the shared V3 lightbox over the
// whole set. Reads data/photos.ts (generated by `npm run sync-gallery`); when it's
// empty the board shows an honest "coming soon" state.
// Short title — the layout template adds the "— Harriet" suffix.
export const metadata: Metadata = {
  title: "Photos",
  description: "The loose board — every unfiled frame, no story to follow.",
  alternates: { canonical: "/photos" },
  openGraph: {
    title: `Photos — ${wordmark}`,
    description: "The loose board — every unfiled frame, no story to follow.",
    url: "/photos",
  },
};

export default function PhotosPage() {
  return (
    <main className="board">
      <header className="board-head">
        <p className="board-eyebrow mono">Unfiled</p>
        <h1 className="board-title">Photos</h1>
        <p className="board-lede">
          Everything else — the frames that didn&rsquo;t need a story to be worth
          keeping. Tap any one to look closer.
        </p>
      </header>
      <PhotosBoard photos={photos} />
    </main>
  );
}
