// =============================================================================
//  site.config.ts — THE ONLY FILE YOU EDIT TO MAKE THIS JOURNAL YOURS
// =============================================================================
//
//  It's all writing and data — no code to change. Edit a value below, run
//  `npm run build`, and it's on the site. No JSX, no className, no imports to
//  chase. Every component only *renders* what lives here. Look for the
//  `CUSTOMIZE:` notes next to the values you'll most likely want to change.
//
//  WHAT'S IN HERE (scan the section banners to jump around):
//    • Identity     — wordmark + canonical URL
//    • Theme        — the vintage-postcard palette + per-mode grounds
//    • Landing      — the blurred hero you open on
//    • Collections  — one entry per trip: a hero + its stacked places
//    • Essays       — the photo-essay prose + figures for each collection
//    • Photos       — the loose board's frames (pre-pipeline stand-ins)
//    • About        — the About-page bio
//
//  ONE THING INTENTIONALLY LIVES ELSEWHERE (generated, not copy):
//    • data/photos.ts — auto-generated by `npm run sync-gallery` in V4 from the
//      real images in public/photos; never hand-edited.
//
//  Privacy: the wordmark is "Harriet" only — no surname anywhere on the site,
//  despite the repo name. It's set once, here, as `wordmark`.
// =============================================================================

// -----------------------------------------------------------------------------
// IDENTITY
// -----------------------------------------------------------------------------
// Canonical identity — the single source of truth for absolute URLs used by
// metadata (metadataBase / canonical / OG) and for the wordmark rendered in the
// nav, footer, landing, and essay signatures.
// CUSTOMIZE: if the production domain ever changes, change it here only.
export const SITE_URL = "https://harrietramus.com";

// CUSTOMIZE: the display name shown everywhere. First-name only, on purpose.
export const wordmark = "Harriet";

// -----------------------------------------------------------------------------
// THEME  (the vintage-postcard palette)
// -----------------------------------------------------------------------------
// The colour system, as data. lib/theme.ts turns this object into the per-mode
// CSS custom properties in one place (themeToCss) — so there are no hand-copied
// hexes in the stylesheet. Two modes: `dark` (deep-ink ground, default) and
// `light` (warm-cream ground). The accent *trio* (tomato / teal / mustard) is
// what makes each collection its own colour — see `accent` on each collection.

/** The three accent hues. Each collection picks one of these keys. */
export interface Trio {
  tomato: string;
  teal: string;
  mustard: string;
}

/** The non-accent "grounds" for one mode — everything that isn't the trio. */
export interface Grounds {
  /** page background */
  bg: string;
  /** raised surface (cards, plates) */
  bg2: string;
  /** primary text */
  ink: string;
  /** secondary text */
  inkSoft: string;
  /** faint text / hairline labels */
  inkFaint: string;
  /** text/icon colour that sits *on* an accent fill */
  accentInk: string;
  /** hairline / divider colour */
  line: string;
  /** translucent sticky-nav background */
  navBg: string;
  /** the lightswitch wall-plate colour */
  plate: string;
}

export interface Theme {
  /** which trio is live. "postcard" is the shipped one. */
  active: "postcard";
  palettes: {
    /** the bright trio used in dark mode */
    postcard: Trio;
    /** deepened trio variants, used in light mode for legibility */
    accentLight: Trio;
    /** alternative single-accent presets — not live, kept for quick reskins */
    presets: Record<string, string>;
  };
  /** which trio hue is the default `--accent` when nothing overrides it */
  defaultAccent: keyof Trio;
  dark: Grounds;
  light: Grounds;
}

// CUSTOMIZE: swap any hex to reskin the whole site. The trio hues drive the
// accent-by-place colour; the grounds drive the two light/dark modes.
export const theme: Theme = {
  active: "postcard",
  defaultAccent: "tomato",
  palettes: {
    // Bright trio — reads on the deep-ink dark ground.
    postcard: {
      tomato: "#d1495b",
      teal: "#3bb3a3",
      mustard: "#e9b64a",
    },
    // Deepened trio — the same hues, darkened so they hold on warm cream.
    accentLight: {
      tomato: "#b23a4b",
      teal: "#2b8677",
      mustard: "#c8912f",
    },
    // Reskin presets: one accent each. Point `defaultAccent`/collections at
    // these only after wiring them into the trio; kept here as a palette shelf.
    presets: {
      teal: "#3bb3a3",
      clay: "#c26b4f",
      slate: "#5b6b7a",
      plum: "#7d5a8c",
      mono: "#8a8272",
    },
  },
  // Dark mode — deep-ink ground, cream ink. The default on first visit.
  dark: {
    bg: "#201d16",
    bg2: "#2a261d",
    ink: "#f3ecdd",
    inkSoft: "#c9c0ad",
    inkFaint: "#8a8272",
    accentInk: "#201d16",
    line: "rgba(243, 236, 221, 0.12)",
    navBg: "rgba(32, 29, 22, 0.72)",
    plate: "#17140f",
  },
  // Light mode — warm-cream ground, deep-ink text.
  light: {
    bg: "#f3ecdd",
    bg2: "#ece3d0",
    ink: "#201d16",
    inkSoft: "#4a4536",
    inkFaint: "#857d69",
    accentInk: "#f3ecdd",
    line: "rgba(32, 29, 22, 0.12)",
    navBg: "rgba(243, 236, 221, 0.72)",
    plate: "#e6dcc6",
  },
};

// -----------------------------------------------------------------------------
// LANDING  (the blurred hero you open on)
// -----------------------------------------------------------------------------
// The full-viewport opening screen. A blurred photo (or the `backdrop` gradient
// fallback) sits behind grain + a scrim; the eyebrow / serif wordmark / tagline
// / subline / scroll-cue sit on top. The real blurred photo lands in V4; until
// then `backdropImage` is "" and the `backdrop` gradient class stands in.

export interface Landing {
  /** small label above the wordmark */
  eyebrow: string;
  /** the big serif line — the wordmark */
  title: string;
  /** one-sentence summary — also used as the site's meta description */
  tagline: string;
  /** the quieter line under the tagline */
  subline: string;
  /** .ph-* gradient class used as the backdrop when backdropImage is "" */
  backdrop: string;
  /** /public path to the real blurred hero photo, or "" for the gradient */
  backdropImage: string;
  /** blur radius (px) applied to backdropImage */
  backdropBlur: number;
  /** the scroll-cue button label */
  cue: string;
}

// CUSTOMIZE: the words on the front door. `title` is the wordmark; `tagline`
// doubles as the SEO description.
export const landing: Landing = {
  eyebrow: "A travel journal",
  title: wordmark,
  tagline: "A journal of places — photographs and short essays from the road.",
  subline: "Africa, the American West, and Japan — collected slowly, one frame at a time.",
  backdrop: "ph-dusk",
  backdropImage: "",
  backdropBlur: 28,
  cue: "Wander in",
};

// -----------------------------------------------------------------------------
// COLLECTIONS  (one entry per trip)
// -----------------------------------------------------------------------------
// The collection wall. Each collection is a full-bleed hero card over a stack of
// thin Place cards, and the whole thing is tinted by ONE trio hue via `accent`
// (Africa → mustard, United States → teal, Japan → tomato). `essay` is the slug
// that links a collection/place into /journal/[essay] (built in V3). `hero` /
// `cls` are .ph-* gradient stand-ins until real photos land in V4.

/** One place inside a collection — a thin stacked card. */
export interface Place {
  /** place name (serif) */
  name: string;
  /** .ph-* gradient stand-in class for this place's photo */
  cls: string;
  /** right-aligned meta label (region / country) */
  meta: string;
  /** the `#code` of the synced photo (data/photos.ts) to show behind this card.
   *  When it resolves, a real next/image renders; otherwise `cls` stands in. */
  code?: string;
}

/** One trip. */
export interface Collection {
  /** collection name (serif title) */
  name: string;
  /** .ph-* gradient stand-in class for the hero photo */
  hero: string;
  /** the stat line; the leading number renders in the mono face + accent */
  stat: string;
  /** slug → /journal/[essay], and the key into `essays` below */
  essay: string;
  /** which trio hue tints this collection */
  accent: keyof Trio;
  /** the `#code` of the synced photo (data/photos.ts) to show behind the hero.
   *  When it resolves, a real next/image renders; otherwise `hero` stands in. */
  code?: string;
  places: Place[];
}

// CUSTOMIZE: add/reorder trips freely. Keep `accent` to a trio key and `essay`
// matching a key in `essays` below (and a route stub) so the links resolve.
export const collections: Collection[] = [
  {
    name: "Africa",
    hero: "ph-savanna",
    stat: "12 days · 3 countries",
    essay: "africa",
    accent: "mustard",
    code: "0001",
    places: [
      { name: "Serengeti", cls: "ph-savanna", meta: "Tanzania", code: "0001" },
      { name: "Ngorongoro", cls: "ph-crater", meta: "Tanzania", code: "0002" },
      { name: "Zanzibar", cls: "ph-sea", meta: "Tanzania", code: "0003" },
    ],
  },
  {
    name: "United States",
    hero: "ph-canyon",
    stat: "9 days · 2,400 miles",
    essay: "united-states",
    accent: "teal",
    code: "0011",
    places: [
      { name: "Moab", cls: "ph-canyon", meta: "Utah", code: "0011" },
      { name: "Big Sur", cls: "ph-coast", meta: "California", code: "0012" },
      { name: "Yosemite", cls: "ph-granite", meta: "California", code: "0013" },
    ],
  },
  {
    name: "Japan",
    hero: "ph-kyoto",
    stat: "14 days · 4 cities",
    essay: "japan",
    accent: "tomato",
    code: "0021",
    places: [
      { name: "Kyoto", cls: "ph-kyoto", meta: "Kansai", code: "0021" },
      { name: "Tokyo", cls: "ph-neon", meta: "Kantō", code: "0022" },
      { name: "Hakone", cls: "ph-fuji", meta: "Kanagawa", code: "0023" },
    ],
  },
];

// -----------------------------------------------------------------------------
// ESSAYS  (the photo-essay for each collection)
// -----------------------------------------------------------------------------
// One essay per collection, keyed by the collection's `essay` slug. The prose
// lives in the MDX bodies (content/essays/*.mdx, V3) — this config holds only
// each essay's identity (title / eyebrow / meta / optional hero) and its ordered
// FIGURE MANIFEST. V6 made that manifest flexible: `figures` is an ordered list
// of ANY length (not the old fixed full/pairA/pairB/end four), rendered in order
// down the V5 single reading column and forming that essay's lightbox set. Each
// figure's `code` is the mono `#code` badge + the synced-photo lookup id; `cls`
// is a .ph-* stand-in shown until a real photo resolves by that code (imported
// essays omit `cls` — their photos land via the Stage 2 checklist).

/** One photograph in an essay — an entry in the ordered reading-flow list. */
export interface EssayFigure {
  /** the mono #code badge — also the lightbox lookup id + synced-photo key */
  code: string;
  /** the caption line */
  cap: string;
  /** aspect ratio (w/h) framing the shot in the lightbox; defaults to 16/10 */
  ratio?: number;
  /** .ph-* gradient stand-in class, shown until a real photo resolves by `code`.
   *  Imported essays omit it (their photos are synced from the checklist). */
  cls?: string;
}

export interface Essay {
  /** small label above the essay title (picks up the collection accent) */
  eyebrow: string;
  /** essay title (serif) */
  title: string;
  /** the hero meta line (place · time) */
  meta: string;
  /** .ph-* stand-in for the sharp lead image; optional (imports omit it) */
  hero?: string;
  /** the ordered figures — any number, rendered full-width in reading order and
   *  forming this essay's lightbox set (index = array position) */
  figures: EssayFigure[];
}

// CUSTOMIZE: reorder / add / remove figures freely — the reading view and the
// lightbox render `figures` in order, however many there are.
export const essays: Record<string, Essay> = {
  africa: {
    eyebrow: "Collection · Africa",
    title: "The long grass",
    meta: "Serengeti, Tanzania · September",
    hero: "ph-savanna",
    figures: [
      {
        code: "0001",
        cap: "First light on the plain, the herd already moving.",
        ratio: 16 / 10,
        cls: "ph-savanna",
      },
      {
        code: "0002",
        cap: "The crater wall at midday, hazed with dust.",
        ratio: 4 / 5,
        cls: "ph-crater",
      },
      {
        code: "0003",
        cap: "Zanzibar, the tide gone all the way out.",
        ratio: 4 / 5,
        cls: "ph-sea",
      },
      {
        code: "0004",
        cap: "Last of the light before we lost the track.",
        ratio: 16 / 10,
        cls: "ph-savanna",
      },
    ],
  },
  "united-states": {
    eyebrow: "Collection · United States",
    title: "West, and keep going",
    meta: "Moab to Big Sur · June",
    hero: "ph-canyon",
    figures: [
      {
        code: "0011",
        cap: "Moab at the hour the walls turn to ember.",
        ratio: 16 / 10,
        cls: "ph-canyon",
      },
      {
        code: "0012",
        cap: "Big Sur, the coast disappearing into its own weather.",
        ratio: 4 / 5,
        cls: "ph-coast",
      },
      {
        code: "0013",
        cap: "Yosemite granite, still cold at noon.",
        ratio: 4 / 5,
        cls: "ph-granite",
      },
      {
        code: "0014",
        cap: "The last pullout before the road turned inland.",
        ratio: 16 / 10,
        cls: "ph-coast",
      },
    ],
  },
  japan: {
    eyebrow: "Collection · Japan",
    title: "Quiet, then neon",
    meta: "Kyoto & Tokyo · November",
    hero: "ph-kyoto",
    figures: [
      {
        code: "0021",
        cap: "A Kyoto side-street after the rain, before the crowds.",
        ratio: 16 / 10,
        cls: "ph-kyoto",
      },
      {
        code: "0022",
        cap: "Tokyo at street level, everything reflected twice.",
        ratio: 4 / 5,
        cls: "ph-neon",
      },
      {
        code: "0023",
        cap: "Fuji from Hakone, through a gap in the cloud.",
        ratio: 4 / 5,
        cls: "ph-fuji",
      },
      {
        code: "0024",
        cap: "Last night in Kyoto, the lanterns just lit.",
        ratio: 16 / 10,
        cls: "ph-kyoto",
      },
    ],
  },
};

// -----------------------------------------------------------------------------
// PHOTOS  (the loose board's frames)
// -----------------------------------------------------------------------------
// The unfiled Photos board — every frame, no captions to read, no story to
// follow. These are pre-pipeline stand-ins: a .ph-* gradient, a location label,
// the mono #code, and the frame's aspect ratio (w/h) so the masonry can lay them
// out. In V4 the real board is generated into data/photos.ts by
// `npm run sync-gallery`; this list is what the board shows until then.

export interface Photo {
  /** .ph-* gradient stand-in class */
  cls: string;
  /** location label shown in the lightbox */
  loc: string;
  /** the mono #code badge / lookup id */
  code: string;
  /** aspect ratio (width / height) for masonry layout */
  ratio: number;
}

// CUSTOMIZE: this list disappears once real photos land in public/photos + the
// sync-gallery run in V4. Until then it keeps the board honest and non-empty.
export const photos: Photo[] = [
  { cls: "ph-savanna", loc: "Serengeti, Tanzania", code: "0001", ratio: 3 / 2 },
  { cls: "ph-sea", loc: "Zanzibar, Tanzania", code: "0003", ratio: 4 / 5 },
  { cls: "ph-crater", loc: "Ngorongoro, Tanzania", code: "0002", ratio: 3 / 2 },
  { cls: "ph-canyon", loc: "Moab, Utah", code: "0011", ratio: 2 / 3 },
  { cls: "ph-coast", loc: "Big Sur, California", code: "0012", ratio: 3 / 2 },
  { cls: "ph-granite", loc: "Yosemite, California", code: "0013", ratio: 1 },
  { cls: "ph-kyoto", loc: "Kyoto, Japan", code: "0021", ratio: 4 / 5 },
  { cls: "ph-neon", loc: "Tokyo, Japan", code: "0022", ratio: 3 / 2 },
  { cls: "ph-fuji", loc: "Hakone, Japan", code: "0023", ratio: 3 / 2 },
];

// -----------------------------------------------------------------------------
// ABOUT
// -----------------------------------------------------------------------------
// The About page — a short bio. First-name signature only (no surname anywhere).

export interface About {
  /** the page title (serif) */
  title: string;
  /** the bio paragraphs */
  paragraphs: string[];
  /** the serif signature line */
  sign: string;
}

// CUSTOMIZE: your own words. Keep `sign` first-name only to honour the privacy
// decision — no surname on the site.
export const about: About = {
  title: "About the journal",
  paragraphs: [
    "I keep this journal the way I travel: slowly, and mostly for myself. It's photographs and short essays from the places a camera has followed me into — the long grass of the Serengeti, the American West at the hour it turns to ember, the quiet-then-neon of Japan.",
    "I'm not trying to sell you a trip. The collections are just how I remember them — one hero, a few places, a little writing — and the loose Photos board is everything else, unfiled, the frames that didn't need a story to be worth keeping.",
    "If a photograph makes you want to go somewhere and pay closer attention when you get there, it's done its whole job. That's the only thing I'm really after here.",
  ],
  sign: "— Harriet",
};
