// AUTO-GENERATED by scripts/sync-gallery.mjs — do not edit directly.
// Add images to public/photos/ (optionally list them in public/photos/gallery.json),
// then run: npm run sync-gallery
//
// The `Photo` type is the V4 board contract: src is the /public image path,
// ratio (width / height) drives the masonry sizing, loc is the hover caption /
// lightbox location, code is the mono #badge / lookup id, and blurDataURL feeds
// next/image's blur-up placeholder.

export type Photo = {
  /** image path in /public */
  src: string;
  /** mono #code badge / lookup id */
  code: string;
  /** location label (hover caption + lightbox) */
  loc: string;
  /** intrinsic aspect ratio, width / height (drives masonry sizing) */
  ratio: number;
  /** base64 blur placeholder for next/image */
  blurDataURL?: string;
};

export const photos: Photo[] = [];
